#!/bin/bash
# (x,y,z)データから一次平面を算出

perl -MMath::BigFloat -alne '{
    $x = $F[0];
    $y = $F[1];
    $z = $F[2];
    $A11 += $x*$x;
    $A12 += $x*$y;
    $A13 += $x;
    $A21 += $x*$y;
    $A22 += $y*$y;
    $A23 += $y;
    $A31 += $x;
    $A32 += $y;
    $A33 += 1;
    $B1  += $x*$z;
    $B2  += $y*$z;
    $B3  += $z;
}END{
    $deno = $A11*$A22*$A33 + $A12*$A23*$A31 + $A13*$A21*$A32
           - $A13*$A22*$A31 - $A12*$A21*$A33 - $A11*$A23*$A32;
    if($deno==0){
        print "error";
        exit;
    }else{
        $rev_deno = 1/$deno;
    }
    $wx = ( ($A22*$A33-$A23*$A32)*$B1 + ($A13*$A32-$A12*$A33)*$B2 + ($A12*$A23-$A13*$A22)*$B3 ) * $rev_deno;
    $wy = ( ($A23*$A31-$A21*$A33)*$B1 + ($A11*$A33-$A13*$A31)*$B2 + ($A13*$A21-$A11*$A23)*$B3 ) * $rev_deno;
    $z  = ( ($A21*$A32-$A22*$A31)*$B1 + ($A12*$A31-$A11*$A32)*$B2 + ($A11*$A22-$A12*$A21)*$B3 ) * $rev_deno;
    print "$wx $wy $z";
}'