#!/bin/bash
# データの線形補間。とりあえずxは整数で、1補間限定

perl -MMath:BigInt -alne '{
    $x[$.]=$F[0];$y[$.]=$F[1];
}END{
    for($i=0;$i<$.;$i++){
        print "$x[$i] $y[$i]";
        if($x[$i+1]-$x[$i]!=1){
            for($k=$x[$i]+1;$k<$x[$i+1];$k++){
                $h=($y[$i+1]-$y[$i])/($x[$i+1]-$x[$i])*$k+($x[$i]*$y[$i+1]-$x[$i+1]*$y[$i])/($x[$i]-$x[$i+1]);
                print "$k $h";
            }
        }
    }
    print "$x[$.] $y[$.]";
}'