#!/bin/bash
# ARG1:deg ARG2:sample ARG3:dimative ARG4:row
#      (1~4)       (3~)        (0~3)
def_deg=2
def_dim=0
def_sample=5
def_row=1
deg=`echo $@ | awk '{for(i=1; i<=NF; i++){if($i=="deg"){print $(i+1);exit;}}print def_deg;}' def_deg=$def_deg `
dim=`echo $@ | awk '{for(i=1; i<=NF; i++){if($i=="dim"){print $(i+1);exit;}}print def_dim;}' def_dim=$def_dim `
sample=`echo $@ | awk '{for(i=1; i<=NF; i++){if($i=="sample"){print $(i+1);exit;}}print def_sample;}' def_sample=$def_sample `
row=`echo $@ | awk '{for(i=1; i<=NF; i++){if($i=="row"){print $(i+1);exit;}}print def_row;}' def_row=$def_row `
awk '
{
    if(deg<1 || sample<3 || dim>3){
        printf("parameter error!!!\n");\
        print deg,sample,dim,NR;\
        exit;\
    }
    d[NR]=$row;org[NR]=$0;\
}END{
    if(NR<3)exit;\
    m=sample; m2=m*m; m4=m2*m2; id=(1-m)/2;\
    # print deg,sample,dim,NR;\

    # deg 0,1  dim : 0 (smoothing)
    if( (deg==0 || deg==1) && dim==0){
        for(i=1; i<=m; i++){
            c[i] = 1/m;\
        }
    }

    # deg : 2,3  dim : 0 (smoothing)
    else if( (deg==2 || deg==3) && dim==0){
        for(i=1; i<=m; i++){
            id2 = id*id;\
            c[i] = (3 * m2 - 7 - 20 * id2) * 3 / (m * (m2 - 4) * 4);\
            id++;\
        }
    }

    # deg : 1,2  dim : 1
    else if( (deg==1 || deg==2) && dim==1){
        for(i=1; i<=m; i++){
            c[i] = id *12 / (m*(m2-1));\
            id++;\
        }
    }

    # deg : 3,4  dim : 1
    else if( (deg == 3 || deg == 4) && dim == 1){
        for(i=1; i<=m; i++){
            id3 = id*id*id;\
            c[i] = (5 * (3 * m4 - 18 * m2 + 31) * id - 28 * (3 * m2 - 7) * id3) * 15 / (m * (m2 - 1) * (3 * m4 - 39 * m2 + 108));\
            id++;\
        }
    }

    # deg : 2,3  dim : 2
    else if(dim == 2){
        for(i=1; i<=m; i++){
            id2 = id*id;\
            c[i] = (12 * m * id2 - m * (m2 - 1)) * 30 / (m2 * (m2 - 1) * (m2 - 4));\
            id++;\
        }
    }

    # deg : 3,4  dim : 3
    else if(dim == 3){
        for(i=1; i<=m; i++){
            id3 = id*id*id;\
            c[i] = ((7 - 3 * m2) * id + 20 * id3) * 2520 / (m * (m2 - 1) * (3 * m4 - 39 * m2 + 108));\
            id++;\
        }
    }

    else{
        print "parameter error";\
        exit;\
    }

    # proccesing
    for(i=1; i<=NR; i++){
        dd=0;\
        if(i>(m-1)/2 && i<=NR-(m-1)/2){
            for(k=1; k<=m; k++){
                dd += c[k] * d[i+k-1+(1-m)/2];\
            }
        }
        print org[i],dd;\
    }
}' deg=$deg sample=$sample dim=$dim row=$row |\
awk '{
    for(i=1; i<NF; i++){
        if(i==row)printf("%g ",$NF);\
        else      printf("%s ",$i);\
    }
    printf("\n");\
}' row=$row