#!/bin/bash
# ??¸ä????¸é?¢ä????°æ???????¾ã??
awk '/./' | awk '! /^#/' |\
awk '{dx[NR]=$1;dy[NR]=$2;}\
     END{for(k=-(int(NR/2));k<0;k++){\
            sqx=0;sqy=0;smx=0;smy=0;smxy=0;\
            for(i=1;i<=NR+k;i++){\
                sqx+=dx[i]**2;\
                sqy+=dy[i-k]**2;\
                smx+=dx[i];\
                smy+=dy[i-k];\
                smxy+=dx[i]*dy[i-k];\
            };\
            r=(smxy-smx*smy/(NR+k))/sqrt((sqx-(smx**2)/(NR+k))*(sqy-(smy**2)/(NR+k)));\
            print k,r;\
            if(max<r){max=r;max_cnt=k;}\
        };\
        for(j=0;j<=int(NR/2);j++){\
            sqx=0;sqy=0;smx=0;smy=0;smxy=0;\
            for(i=1;i<=NR-j;i++){\
                sqx+=dx[i+j]**2;\
                sqy+=dy[i]**2;\
                smx+=dx[i+j];\
                smy+=dy[i];\
                smxy+=dx[i+j]*dy[i];\
            };\
            r=(smxy-smx*smy/(NR-j))/sqrt((sqx-(smx**2)/(NR-j))*(sqy-(smy**2)/(NR-j)));\
            print j,r;\
            if(max<r){max=r;max_cnt=j;}\
        };\
        printf("# max : %f, ind : %d",max,max_cnt);\
     }'
